# Team C3 
<br> **Group members:** 
- Chad Pranke
- Eric Choi 
- Jenny Theresia

## Datasets

The following datasets consist of historical hourly temperature data between 2012 and 2017 for 30 US & Canadian Cities and 6 Israeli Cities. We hope to analyze the temperature changes in these cities over the years.

<br> **Source:**

The data was obtained from https://www.kaggle.com/selfishgene/historical-hourly-weather-data#wind_speed.csv. The author states the original input data was aquired by using Weather API on the OpenWeatherMap website, and is available under the ODbL License.

In [1]:
import numpy as np 
import pandas as pd

In [2]:
filename = 'temperature.csv'

In [3]:
f = open(filename,'r')

In [4]:
reader = pd.read_csv(f,",")

In [5]:
reader

,datetime,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,...,Philadelphia,New York,Montreal,Boston,Beersheba,Tel Aviv District,Eilat,Haifa,Nahariyya,Jerusalem
0,2012-10-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,309.100000,NaN,NaN,NaN
1,2012-10-01 13:00:00,284.630000,282.080000,289.480000,281.800000,291.870000,291.530000,293.410000,296.600000,285.120000,...,285.630000,288.220000,285.830000,287.170000,307.590000,305.470000,310.580000,304.4,304.4,303.5
2,2012-10-01 14:00:00,284.629041,282.083252,289.474993,281.797217,291.868186,291.533501,293.403141,296.608509,285.154558,...,285.663208,288.247676,285.834650,287.186092,307.590000,304.310000,310.495769,304.4,304.4,303.5
3,2012-10-01 15:00:00,284.626998,282.091866,289.460618,281.789833,291.862844,291.543355,293.392177,296.631487,285.233952,...,285.756824,288.326940,285.847790,287.231672,307.391513,304.281841,310.411538,304.4,304.4,303.5
4,2012-10-01 16:00:00,284.624955,282.100481,289.446243,281.782449,291.857503,291.553209,293.381213,296.654466,285.313345,...,285.850440,288.406203,285.860929,287.277251,307.145200,304.238015,310.327308,304.4,304.4,303.5
5,2012-10-01 17:00:00,284.622911,282.109095,289.431869,281.775065,291.852162,291.563063,293.370249,296.677445,285.392738,...,285.944057,288.485467,285.874069,287.322831,306.898887,304.194188,310.243077,304.4,304.4,303.5
6,2012-10-01 18:00:00,284.620868,282.117710,289.417494,281.767681,291.846821,291.572917,293.359284,296.700424,285.472132,...,286.037673,288.564730,285.887208,287.368410,306.652574,304.150361,310.158846,304.4,304.4,303.5
7,2012-10-01 19:00:00,284.618824,282.126324,289.403119,281.760297,291.841480,291.582772,293.348320,296.723403,285.551525,...,286.131290,288.643994,285.900348,287.413990,306.406261,304.106534,310.074615,304.4,304.4,303.5
8,2012-10-01 20:00:00,284.616781,282.134939,289.388745,281.752912,291.836139,291.592626,293.337356,296.746381,285.630919,...,286.224906,288.723257,285.913487,287.459569,306.159948,304.062708,309.990385,304.4,304.4,303.5
9,2012-10-01 21:00:00,284.614738,282.143553,289.374370,281.745528,291.830798,291.602480,293.326392,296.769360,285.710312,...,286.318522,288.802521,285.926627,287.505149,305.913635,304.018881,309.906154,304.4,304.4,303.5
10,2012-10-01 22:00:00,284.612694,282.152168,289.359995,281.738144,291.825457,291.612334,293.315428,296.792339,285.789705,...,286.412139,288.881784,285.939767,287.550728,305.667322,303.975054,309.821923,304.4,304.4,303.5
11,2012-10-01 23:00:00,284.610651,282.160782,289.345621,281.730760,291.820116,291.622188,293.304463,296.815318,285.869099,...,286.505755,288.961048,285.952906,287.596308,305.421008,303.931228,309.737692,304.4,304.4,303.5
12,2012-10-02 00:00:00,284.608607,282.169397,289.331246,281.723376,291.814775,291.632042,293.293499,296.838297,285.948492,...,286.599371,289.040311,285.966046,287.641887,305.174695,303.887401,309.653462,304.4,304.4,303.5
13,2012-10-02 01:00:00,284.606564,282.178011,289.316871,281.715992,291.809434,291.641896,293.282535,296.861275,286.027886,...,286.692988,289.119575,285.979185,287.687467,304.928382,303.843574,309.569231,304.4,304.4,303.5
14,2012-10-02 02:00:00,284.604521,282.186626,289.302496,281.708608,291.804093,291.651750,293.271571,296.884254,286.107279,...,286.786604,289.198838,285.992325,287.733046,304.682069,303.799747,309.485000,304.4,304.4,303.5
15,2012-10-02 03:00:00,284.602477,282.195240,289.288122,281.701224,291.798752,291.661605,293.260606,296.907233,286.186673,...,286.880220,289.278102,286.005465,287.778626,304.435756,303.755921,309.400769,304.4,304.4,303.5
16,2012-10-02 04:00:00,284.600434,282.203855,289.273747,281.693840,291.793411,291.671459,293.249642,296.930212,286.266066,...,286.973837,289.357365,286.018604,287.824205,304.189443,303.712094,309.316538,304.4,304.4,303.5
17,2012-10-02 05:00:00,284.598390,282.212469,289.259372,281.686456,291.788070,291.681313,293.238678,296.953191,286.345459,...,287.067453,289.436629,286.031744,287.869785,303.943130,303.668267,309.232308,304.4,304.4,303.5
18,2012-10-02 06:00:00,284.596347,282.221084,289.244998,281.679072,291.782729,291.691167,293.227714,296.976170,286.424853,...,287.161069,289.515892,286.044883,287.915364,303.696817,303.624440,309.148077,304.4,304.4,303.5
19,2012-10-02 07:00:00,284.594304,282.229698,289.230623,281.671688,291.777387,291.701021,293.216750,296.999148,286.504246,...,287.254686,289.595156,286.058023,287.960944,303.450504,303.580614,309.063846,304.4,304.4,303.5
20,2012-10-02 08:00:00,284.592260,282.238313,289.216248,281.664304,291.772046,291.710875,293.205785,297.022127,286.583640,...,287.348302,289.674419,286.071162,288.006523,303.204191,303.536787,308.979615,304.4,304.4,303.5
21,2012-10-02 09:00:00,284.590217,282.246927,289.201874,281.656920,291.766705,291.720729,293.194821,297.045106,286.663033,...,287.441918,289.753683,286.084302,288.052103,302.957878,303.492960,308.895385,304.4,304.4,303.5
22,2012-10-02 10:00:00,284.588174,282.255542,289.187499,281.649536,291.761364,291.730583,293.183857,297.068085,286.742426,...,287.535535,289.832946,286.097442,288.097682,302.711565,303.449134,308.811154,304.4,304.4,303.5
23,2012-10-02 11:00:00,284.586130,282.264156,289.173124,281.642152,291.756023,291.740438,293.172893,297.091064,286.821820,...,287.629151,289.912210,286.110581,288.143262,302.465252,303.405307,308.726923,304.4,304.4,303.5
24,2012-10-02 12:00:00,284.584087,282.272771,289.158749,281.634768,291.750682,291.750292,293.161928,297.114042,286.901213,...,287.722767,289.991473,286.123721,288.188841,302.218939,303.361480,308.642692,304.4,304.4,303.5
25,2012-10-02 13:00:00,284.582043,282.281385,289.144375,281.627384,291.745341,291.760146,293.150964,297.137021,286.980607,...,287.816384,290.070737,286.136860,288.234421,301.972626,303.317653,308.558462,304.4,304.4,303.5
26,2012-10-02 14:00:00,284.580000,282.290000,289.130000,281.620000,291.740000,291.770000,293.140000,297.160000,287.060000,...,287.910000,290.150000,286.150000,288.280000,301.726313,303.273827,308.474231,304.4,304.4,303.5
27,2012-10-02 15:00:00,284.850000,282.510000,290.730000,282.710000,293.970000,294.910000,296.380000,300.760000,289.910000,...,290.580000,291.320000,287.550000,289.540000,301.480000,303.230000,308.390000,304.4,304.4,303.5
28,2012-10-02 16:00:00,286.260000,284.440000,293.020000,285.050000,295.590000,296.300000,297.020000,303.480000,291.470000,...,291.700000,291.780000,288.140000,289.780000,300.925000,302.770000,307.350000,304.4,304.4,303.5
29,2012-10-02 17:00:00,286.770000,287.860000,296.180000,287.970000,297.930000,300.130000,300.240000,306.320000,292.860000,...,292.570000,292.740000,288.690000,290.440000,300.370000,301.610000,305.870000,304.4,304.4,303.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45223,2017-11-28 19:00:00,NaN,280.400000,NaN,279.750000,292.460000,289.840000,288.150000,291.820000,285.460000,...,287.810000,NaN,272.750000,277.070000,NaN,NaN,NaN,NaN,NaN,NaN
45224,2017-11-28 20:00:00,NaN,280.150000,NaN,279.850000,294.740000,291.690000,289.340000,293.480000,286.410000,...,287.870000,NaN,273.750000,277.910000,NaN,NaN,NaN,NaN,NaN,NaN
45225,2017-11-28 21:00:00,NaN,280.400000,NaN,280.150000,295.970000,291.760000,289.750000,294.370000,286.480000,...,287.060000,NaN,274.050000,277.850000,NaN,NaN,NaN,NaN,NaN,NaN
45226,2017-11-28 22:00:00,NaN,280.410000,NaN,280.150000,296.740000,292.080000,289.470000,295.150000,286.430000,...,287.070000,NaN,274.050000,277.150000,NaN,NaN,NaN,NaN,NaN,NaN
45227,2017-11-28 23:00:00,NaN,280.150000,NaN,279.150000,289.157000,290.082000,283.482000,295.150000,286.150000,...,284.620000,NaN,279.057000,277.150000,NaN,NaN,NaN,NaN,NaN,NaN
45228,2017-11-29 00:00:00,NaN,280.650000,NaN,279.150000,295.480000,291.010000,289.480000,295.590000,283.870000,...,283.070000,NaN,274.730000,275.650000,NaN,NaN,NaN,NaN,NaN,NaN
45229,2017-11-29 01:00:00,NaN,280.030000,NaN,279.260000,293.760000,290.400000,288.150000,295.150000,281.110000,...,282.400000,NaN,275.030000,276.070000,NaN,NaN,NaN,NaN,NaN,NaN
45230,2017-11-29 02:00:00,NaN,280.160000,NaN,278.940000,292.470000,289.840000,286.510000,293.020000,279.820000,...,281.780000,NaN,274.350000,276.890000,NaN,NaN,NaN,NaN,NaN,NaN
45231,2017-11-29 03:00:00,NaN,279.770000,NaN,278.850000,291.210000,288.430000,285.480000,290.480000,278.580000,...,281.510000,NaN,275.000000,278.070000,NaN,NaN,NaN,NaN,NaN,NaN
45232,2017-11-29 04:00:00,NaN,279.900000,NaN,278.640000,290.420000,287.760000,283.420000,289.150000,276.790000,...,281.160000,NaN,275.700000,279.140000,NaN,NaN,NaN,NaN,NaN,NaN
45233,2017-11-29 05:00:00,NaN,279.650000,NaN,278.840000,289.340000,287.140000,283.090000,288.270000,276.530000,...,280.990000,NaN,276.380000,279.810000,NaN,NaN,NaN,NaN,NaN,NaN
45234,2017-11-29 06:00:00,NaN,279.030000,NaN,278.740000,289.070000,286.640000,282.580000,287.980000,275.480000,...,280.740000,NaN,275.720000,281.320000,NaN,NaN,NaN,NaN,NaN,NaN
45235,2017-11-29 07:00:00,NaN,279.030000,NaN,278.560000,288.420000,286.600000,282.420000,286.640000,274.500000,...,280.970000,NaN,275.770000,282.230000,NaN,NaN,NaN,NaN,NaN,NaN
45236,2017-11-29 08:00:00,NaN,278.520000,NaN,278.920000,287.220000,286.490000,282.020000,286.680000,274.560000,...,280.560000,NaN,275.380000,282.540000,NaN,NaN,NaN,NaN,NaN,NaN
45237,2017-11-29 09:00:00,NaN,278.420000,NaN,279.050000,286.550000,286.640000,281.710000,287.010000,272.870000,...,280.320000,NaN,277.450000,283.080000,NaN,NaN,NaN,NaN,NaN,NaN
45238,2017-11-29 10:00:00,NaN,277.780000,NaN,278.920000,286.220000,286.430000,283.350000,286.670000,272.170000,...,279.400000,NaN,278.770000,283.660000,NaN,NaN,NaN,NaN,NaN,NaN
45239,2017-11-29 11:00:00,NaN,278.400000,NaN,278.260000,285.220000,285.780000,283.120000,286.680000,271.880000,...,279.060000,NaN,278.480000,283.980000,NaN,NaN,NaN,NaN,NaN,NaN
45240,2017-11-29 12:00:00,NaN,278.540000,NaN,278.540000,284.550000,285.680000,281.550000,286.010000,270.870000,...,278.480000,NaN,277.450000,283.530000,NaN,NaN,NaN,NaN,NaN,NaN
45241,2017-11-29 13:00:00,NaN,278.660000,NaN,278.050000,284.220000,285.060000,281.560000,285.950000,269.170000,...,279.770000,NaN,276.160000,283.990000,NaN,NaN,NaN,NaN,NaN,NaN
45242,2017-11-29 14:00:00,NaN,278.540000,NaN,277.960000,283.630000,285.520000,280.560000,286.040000,271.170000,...,282.510000,NaN,276.480000,284.240000,NaN,NaN,NaN,NaN,NaN,NaN
45243,2017-11-29 15:00:00,NaN,278.400000,NaN,278.230000,283.210000,285.280000,281.550000,286.040000,271.270000,...,285.330000,NaN,277.450000,284.650000,NaN,NaN,NaN,NaN,NaN,NaN
45244,2017-11-29 16:00:00,NaN,278.650000,NaN,278.660000,282.930000,285.750000,280.970000,286.640000,275.360000,...,287.500000,NaN,278.130000,285.480000,NaN,NaN,NaN,NaN,NaN,NaN
45245,2017-11-29 17:00:00,NaN,279.270000,NaN,278.240000,285.640000,287.600000,282.960000,288.390000,278.640000,...,289.470000,NaN,277.700000,286.910000,NaN,NaN,NaN,NaN,NaN,NaN
45246,2017-11-29 18:00:00,NaN,280.440000,NaN,278.530000,289.020000,289.640000,285.350000,290.920000,280.910000,...,290.070000,NaN,276.150000,288.650000,NaN,NaN,NaN,NaN,NaN,NaN
45247,2017-11-29 19:00:00,NaN,281.520000,NaN,280.030000,292.030000,290.930000,287.520000,293.150000,283.210000,...,290.150000,NaN,276.450000,289.160000,NaN,NaN,NaN,NaN,NaN,NaN
45248,2017-11-29 20:00:00,NaN,282.000000,NaN,280.820000,293.550000,292.150000,289.540000,294.710000,285.720000,...,290.240000,NaN,275.130000,288.080000,NaN,NaN,NaN,NaN,NaN,NaN
45249,2017-11-29 21:00:00,NaN,282.890000,NaN,281.650000,295.680000,292.740000,290.610000,295.590000,286.450000,...,289.240000,NaN,274.130000,286.020000,NaN,NaN,NaN,NaN,NaN,NaN
45250,2017-11-29 22:00:00,NaN,283.390000,NaN,282.750000,295.960000,292.580000,291.340000,296.250000,286.440000,...,286.780000,NaN,273.480000,283.940000,NaN,NaN,NaN,NaN,NaN,NaN
45251,2017-11-29 23:00:00,NaN,283.020000,NaN,282.960000,295.650000,292.610000,292.150000,297.150000,286.140000,...,284.570000,NaN,272.480000,282.170000,NaN,NaN,NaN,NaN,NaN,NaN
45252,2017-11-30 00:00:00,NaN,282.280000,NaN,283.040000,294.930000,291.400000,291.640000,297.150000,284.700000,...,283.420000,NaN,271.800000,280.650000,NaN,NaN,NaN,NaN,NaN,NaN